apiVersion: v1
kind: Service
metadata:
  name: my-test
spec:
  selector:
    app.kubernetes.io/name: my-test
  type: NodePort
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 3005
    targetPort: 80
    nodePort: 31600